routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use Laravel\Socialite\Facades\Socialite;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
// Route::get('dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard')->middleware('is_admin');
// Route::get('/', [App\Http\Controllers\HomeController::class, 'adminHome']);

Auth::routes();

//Logout
Route::get('logout', [App\Http\Controllers\Auth\LoginController::class ,'loggedOut'])->name('logout');


//SocialMedia Login
//Google
Route::get('login/google', [App\Http\Controllers\Auth\LoginController::class ,'redirectToProvider'])->name('login/google');
Route::get('login/google/callback', [App\Http\Controllers\Auth\LoginController::class,'handleProviderCallback'])->name('login/google/callback');

//Facebook
Route::get('login/facebook', [App\Http\Controllers\Auth\LoginController::class ,'redirectToFacebook'])->name('login/facebook');
Route::get('login/facebook/callback', [App\Http\Controllers\Auth\LoginController::class,'handleFacebookCallback'])->name('login/facebook/callback');

//Linkedin
Route::get('login/linkedin', [App\Http\Controllers\Auth\LoginController::class ,'redirectToLinkedin'])->name('login/linkedin');
Route::get('login/linkedin/callback', [App\Http\Controllers\Auth\LoginController::class,'handleLinkedinCallback'])->name('login/linkedin/callback');

//Twitter
Route::get('login/twitter', [App\Http\Controllers\Auth\LoginController::class ,'redirectToTwitter'])->name('login/twitter');
Route::get('login/twitter/callback', [App\Http\Controllers\Auth\LoginController::class,'handleTwitterCallback'])->name('login/twitter/callback');

//Github
Route::get('login/github', [App\Http\Controllers\Auth\LoginController::class ,'redirectToGithub'])->name('login/github');
Route::get('login/github/callback', [App\Http\Controllers\Auth\LoginController::class,'handleGithubCallback'])->name('login/github/callback');

//Customer
Route::get('/customer', [App\Http\Controllers\CustomerController::class, 'index'])->name('customer');
Route::get('/create', [App\Http\Controllers\CustomerController::class, 'create'])->name('CreateCustomer');
Route::post('/store', [App\Http\Controllers\CustomerController::class, 'store'])->name('StoreCustomer');
Route::get('/edit/{id}', [App\Http\Controllers\CustomerController::class, 'edit'])->name('EditCustomer');
Route::post('/update/{id}', [App\Http\Controllers\CustomerController::class, 'update'])->name('UpdateCustomer');
Route::delete('/delete/{id}', [App\Http\Controllers\CustomerController::class, 'destroy'])->name('DeleteCustomer');

//User
Route::resource('/user', App\Http\Controllers\UserController::class);

//Stripe Payment
Route::get('stripe', [App\Http\Controllers\PaymentController::class, 'stripe']);
Route::post('stripe', [App\Http\Controllers\PaymentController::class, 'stripePost'])->name('stripe.post');


//Rozorpay Payment
Route::get('razorpay', [App\Http\Controllers\PaymentController::class, 'razorpay']);
Route::post('razorpay', [App\Http\Controllers\PaymentController::class, 'razorpayPost'])->name('razorpay.post');

//PayPal Payment
Route::get('paypal', [App\Http\Controllers\PaymentController::class, 'paypal']);
Route::get('cancel', [App\Http\Controllers\PaymentController::class, 'cancel'])->name('paypal.cancel');
Route::get('paypal/paypalPost', [App\Http\Controllers\PaymentController::class, 'paypalPost'])->name('paypal.success');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use App\Models\User;
use Illuminate\Support\Facades\Hash;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['user']=DB::table('users')->get();
        $data['title']='User ';
        $data['routes'] = "user";
        $data['pagetitle'] = 'User | Laravel8 Demo'; 
        return view('admin.User.user',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['subtitle'] ='Create User';
        $data['title']='User ';
        $data['routes'] = "user";
        $data['pagetitle'] = 'User | Laravel8 Demo'; 
        return view('admin.User.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       // echo"<pre>"; print_r($request->all()); exit();
        $this->validate($request,[
             'name' => 'required',
            'email' => 'required',
            'email' => 'unique:users|max:255',
            'password' => 'required|min:8',
           ]);
    
        

        $res = new User;
        $res->name = ucwords($request->input('name'));
        $res->email = trim($request->input('email'));
        $res->password = Hash::make($request->input('password'));
        // echo "<pre>"; print_r($res); exit();
        $res->save();
       
        if($res)
        {
            request()->session()->flash('success','User created successfully.');
        }
        else {
            request()->session()->flash('error','Something Went Wrong Please Try Again.');
        }
        return redirect('suser.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $result['title'] = 'User List';
        $result['subtitle'] = 'Edit User';
        $result['routes'] = "users";
        $result['pagetitle'] = 'Edit User | Laravel8 Demo';
        $result['editdata'] = User::find($id);
        return view('admin/user/edit',$result);   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // echo "<pre>"; print_r($request->all()); exit();
            
        //     $this->validate($request,[
        //     'name' => 'required',
        //     'email' => 'required|email|unique:users,email,'.$id,

        //    ]);
    
       
        $res =User::find($id);
        $res->name = ucwords($request->input('name'));
        $res->email = trim($request->input('email'));
        
        if(isset($password) && $password != ''){
        $res->password = Hash::make($request->input('password'));
     }
        $res->save();
       
        if($res)
        {
            request()->session()->flash('success','User Updated successfully.');
        }
        else {
            request()->session()->flash('error','Something Went Wrong Please Try Again.');
        }
        return redirect('user');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=User::findorFail($id);

       $status=$user->delete();
       
        if($status){
            request()->session()->flash('success','User deleted successfully.');
        }
        else{
            request()->session()->flash('error','Error while deleting user');
        }
        
        return redirect('user.index');
    }
}

resources/views/admin/User/create.blade.php
@include('admin.layouts.stylesheet')
<!-- Navbar -->
@include('admin.layouts.navbar')
<!-- /.navbar -->
<!-- Main Sidebar Container -->
@include('admin.layouts.mainsidebar')
<div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <div class="content-header">
      <div class="container-fluid">
         <div class="row mb-2">
            <div class="col-sm-6">
               <h1 class="m-0 text-dark">{{$subtitle}}</h1>
            </div>
            <!-- /.col -->
            <!-- Content Wrapper. Contains page content -->
            @include('admin.layouts.breadcrumb')
         </div>
         <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
   </div>
   <section class="content">
      <div class="row">
         <div class="col-12">
            <div class="card">
               <!-- /.card-header -->
               <div class="card-body">
                  <h3 class="card-title float-right">
                     <a title="Back" href="{{route('user.index')}}"><button title="Back" type="button" class="btn btn-block btn-primary">Back</button></a>
                  </h3>
                  <br>
                  <div class="col-xl-10 col-lg-6 col-md-8 col-sm-10 mx-auto">
                     <br>
                     
                     <!-- /.card-header -->
                     <!-- form start -->
                     <div class="card card-primary ">
                        <div class="card-header">
                           <h3 class="card-title">Create User</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form class="form-horizontal" action="{{route('user.store')}}" method="post" enctype="multipart/form-data">
                           @csrf
                           <div class="card-body">
                              <div class="form-group">
                                 <label for="name">Name <span class="mendatory">*</span></label>
                                 <input class="form-control" id="nametext"  type="text" name="name" placeholder="Enter name" value="{{old('name')}}"  autocomplete="name" required>
                                 @error('name')
                                 <span class="text-danger">{{$message}}</span>
                                 @enderror
                              </div>
                              <div class="form-group">
                                 <label for="email">Email  <span class="mendatory">*</span></label>
                                 <input class="form-control" id="email" value="{{old('email')}}"   pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" type="email" name="email" placeholder="Enter email" autocomplete="email" required>
                                 @error('email')
                                 <span class="text-danger">{{$message}}</span>
                                 @enderror
                              </div>
                            
                              <div class="form-group">
                                 <label for="password">Password  <span class="mendatory">*</span></label>
                                 <input class="form-control" id="password" type="text" value="{{old('password')}}"  name="password" placeholder="Enter password" autocomplete="password" minlength="8" required>
                                 @error('password')
                                 <span class="text-danger">{{$message}}</span>
                                 @enderror
                              </div>
                            </div> 
                           <!-- /.card-body -->
                           <div class="card-footer">
                              <button type="submit" class="btn btn-primary">Submit</button>
                              <button type="reset" class="btn btn-warning">Reset</button>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </section>
   <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@include('admin.layouts.footer')
<!-- ./wrapper -->
<!-- jQuery -->
@include('admin.layouts.scripts')

resources/views/admin/User/edit.blade.php
@include('admin.layouts.stylesheet')
<!-- Navbar -->
@include('admin.layouts.navbar')
<!-- /.navbar -->
<!-- Main Sidebar Container -->
@include('admin.layouts.mainsidebar')
<div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <div class="content-header">
      <div class="container-fluid">
         <div class="row mb-2">
            <div class="col-sm-6">
               <h1 class="m-0 text-dark">{{$subtitle}}</h1>
            </div>
            <!-- /.col -->
            <!-- Content Wrapper. Contains page content -->
            @include('admin.layouts.breadcrumb')
         </div>
         <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
   </div>
   <!-- /.content-header -->
   <section class="content">
      <div class="row">
         <div class="col-12">
            <div class="card">
               <!-- /.card-header -->
               <div class="card-body">
                  <h3 class="card-title float-right">
                     <a data-toggle="tooltip" title="Back"  href="{{route('user.index')}}"><button type="button" class="btn btn-block btn-primary">Back</button></a>
                  </h3>
                  <br>
                  <div class="col-xl-10 col-lg-6 col-md-8 col-sm-10 mx-auto">
                     <br>
                     
                     <!-- /.card-header -->
                     <!-- form start -->
                     <div class="card card-primary ">
                        <div class="card-header">
                           <h3 class="card-title">Edit User</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form class="form-horizontal" action="{{route('user.update',[$editdata->id])}}" method="post" enctype="multipart/form-data">
                           @csrf
                                   @method('PUT')

                           <div class="card-body">
                              <div class="form-group">
                                 <label for="exampleInputEmail1"> Name <span class="mendatory">*</span></label>
                                 <input class="form-control" id="nametext"  type="text" name="name" placeholder="Enter name" autocomplete="name"  value="{{$editdata->name}}"  required>
                                 @error('name')
                                 <span class="text-danger">{{$message}}</span>
                                 @enderror
                              </div>
                              <div class="form-group">
                                 <label for="exampleInputPassword1">Email  <span class="mendatory">*</span></label>
                                 <input class="form-control" id="email"  pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" type="email" name="email" placeholder="Enter email"  autocomplete="email"   value="{{$editdata->email}}" required>
                                 @error('email')
                                 <span class="text-danger">{{$message}}</span>
                                 @enderror
                              </div>
                             
                              <div class="form-group">
                                 <label for="exampleInputPassword1">Update Password  <span class="mendatory">*</span></label>
                                 <input class="form-control" id="password" type="text" name="password" placeholder="Enter password" autocomplete="password" minlength="8" >
                                 @error('password')
                                 <span class="text-danger">{{$message}}</span>
                                 @enderror
                              </div>
                           <!-- /.card-body -->
                           <div class="card-footer">
                              <button title="Update" type="submit" class="btn btn-success">Update</button>
                              <h3 class="card-title float-right">
                     <a data-toggle="tooltip" title="Cancle"  href="{{route('user.index')}}"><button type="button" class="btn btn-block btn-primary">Cancle</button></a>
                  </h3>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </section>
   <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@include('admin.layouts.footer')
<!-- ./wrapper -->
<!-- jQuery -->
@include('admin.layouts.scripts')

resources/views/admin/User/user.blade.php
  @include('admin.layouts.stylesheet')
<!-- Navbar -->
@include('admin.layouts.navbar')
<!-- /.navbar -->
<!-- Main Sidebar Container -->
@include('admin.layouts.mainsidebar')
<div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <div class="content-header">
      <div class="container-fluid">
         <div class="row mb-2">
            <div class="col-sm-6">
               <h1 class="m-0 text-dark">{{$title}}</h1>
            </div>
            <!-- /.col -->
            <!-- Content Wrapper. Contains page content -->
            @include('admin.layouts.breadcrumb')
         </div>
         <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
   </div>
   <!-- /.content-header -->
   <!-- Main content -->
   <section class="content">
      <div class="row">
         <div class="col-12">
            <div class="row">
               <div class="col-md-12">
                  @include('admin.layouts.notification')
               </div>
            </div>
            <div class="card">
               <div class="card-header">
                  <h3 class="card-title float-right"> <a title="Create User" href="{{route('user.create')}}">
                     <button type="
                        button" title="Create User" class="btn btn-block btn-primary"> Create User</button></a>
                  </h3>
               </div>
               <!-- /.card-header -->
               <div class="card-body">
                  <label id="convertmsg" class="col-md-8  alert-success"></label>
                  <table id="example1" class="table table-bordered table-striped">
                     <thead>
                        <tr>
                            <th>Id</th>
                           <th>Name</th>
                           <th>Email</th>
                          <!--  <th>Role</th> -->
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                        @foreach($user as $users)
                      
                        <tr>
                           <td class="text-center">{{$users->id}}</td>
                           <td class="text-center">{{$users->name}}</td>
                           <td class="text-center">{{$users->email}}</td>
                           <td>
                           
                   <a class="btn btn-primary btn-sm " style="height:30px; width:30px;border-radius:50%"  title="Edit" href="{{route('user.edit',$users->id)}}"><i class="fa fa-edit"></i></a>
                <form action="{{ route('DeleteCustomer',$users->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger btn-sm " style="height:30px; width:30px;border-radius:50%"  title="Delete" href="{{route('user.destroy',$users->id)}}" onclick="return confirm('Are you sure to delete?')"><i class="fa fa-trash"></i></button>
                 
                </form>
            </td>
            @endforeach
                     </tbody>
                  </table>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </section>
   <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@include('admin.layouts.footer')
<!-- ./wrapper -->
<!-- jQuery -->
@include('admin.layouts.scripts')
<style type="text/css">
   button.btn.active.btn-Active.btn-md {
   font-size: 10px;
   padding: 4px;
   background-color: green !important;
   }
</style>